language: node_js
# sudo: required

node_js:
  - "12"
  
env:
  DEBUG: 'http2'
  
script: npm test -- --all
notifications:
  email:
    on_success: change
    on_failure: change

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

# before_install:
#   - npm install -g npm@latest
  
cache:
  directories:
    - node_modules
    
